name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: gate.snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: maven

      # Override http://repo.gate.ac.uk to use https:// instead
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          mirrors: '[{"id": "gate.ac.uk-https", "name": "GATE repo (secure)", "mirrorOf": "gate.ac.uk", "url": "https://repo.gate.ac.uk/content/groups/public/"}]'

      - name: Build with Maven
        run: mvn --batch-mode -e clean install 

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          fail_if_no_tests: false
          
      - name: Build site
        run: mvn --batch-mode -e -DskipTests site

      - name: Publish FindBugs Report
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/findbugsXml.xml'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'target/site'

      - name: Deploy to repo.gate.ac.uk
        run: mvn -e -Dmaven.test.skip=true source:jar javadoc:jar deploy
        env:
          MAVEN_USERNAME: ${{ secrets.GATE_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GATE_REPO_PASSWORD }}

      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
