name: Henderson CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: gate.snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          
      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -e clean install

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          fail_if_no_tests: false
      
      - name: Publish Jacoco Code Coverage Report
        uses: codecov/codecov-action@v2
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
          dry_run: true

      - name: Deploy to repo.gate.ac.uk
        run: mvn -e -Dmaven.test.skip=true source:jar javadoc:jar deploy
        env:
          MAVEN_USERNAME: ${{ secrets.GATE_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GATE_REPO_PASSWORD }}
